spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
      
logging:
  level:
    com.thresholdsign: DEBUG
    root: INFO

startup:
    message: "About to run the Threshold Signing Simulation"
    T: 4
    N: 7
    nodes: "1,3,4,6"
    stringToSign: "test"
